### PR TITLE
responsive design in progress

### PR DESCRIPTION
**Pull request by miteshree**
added .vs to gitignore
responsive navigation

### CODE REVIEW

**Comment by miteshree** [comment]
Tried to add few changes to make it responsive. Have changed the design of navigation bar in order to make it fixed at top.

**Comment by miteshree** [comment]
@Contrevien as discussed in the other thread, we won't be using bootstrap correct? So, I will make changes accordingly. You haven't merged this branch to master yet?

**Comment by miteshree** [comment]
@Contrevien quick question, so for navigation bar also we are not using bootstrap?

**Comment by Contrevien** [comment]
@miteshree Try using flexbox or grid wherever possible or plain CSS.

**Pull request merged**
